INSERT INTO CURRENCY_VALUE  (ID ,CURRENCY_MULTIPLY ,CURRENCY_FROM ,CURRENCY_TO )
VALUES (1, 400, 'eth', 'usd');

INSERT INTO CURRENCY_VALUE  (ID ,CURRENCY_MULTIPLY ,CURRENCY_FROM ,CURRENCY_TO )
VALUES (2, 12000, 'btc', 'usd');