insert into CURRENCY_VALUE (ID ,CURRENCY_MULTIPLIER ,CURRENCY_FROM ,CURRENCY_TO ) values (1, 12000, 'btc', 'usd');
insert into CURRENCY_VALUE (ID ,CURRENCY_MULTIPLIER ,CURRENCY_FROM ,CURRENCY_TO ) values (2, 4000, 'eth', 'usd');
